version: '3.9'
services:
  db:
    image: mysql
    container_name: mysqldb
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'sneakerhead-API'
    networks:
      - default_network
    # healthcheck:
    #   test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  app:
    build:
      context: ./
    container_name: sneakerhead-API
    ports:
      - '3333:3333'
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=sneakerhead-API
      - DB_PORT=3306
    restart: always
    networks:
      - default_network
    depends_on:
      - db
      # :
      #   condition: service_healthy

networks:
  default_network:
    driver: bridge
